### ISSUE TITLE
Hide passwords

### ISSUE THREAD

**Issue by RayBenefield** [dbmrq/vim-redacted#1]
Would it be possible to use this in combination with say a regex expression to hide passwords and stuff in a JSON file. I've done live code streaming a few times and the risk of showing a password/secret is real. Wondering if this could help with that use case.

**Comment by dbmrq** [comment]
There you go, with the latest version you can use `:call Redact('pattern')` to redact all text matching a regex expression.

Just keep in mind that the text will still be visible if you select it in visual mode, so you'd have to double check for that when recording sensitive information. :)

**Comment by RayBenefield** [comment]
Much appreciated @dbmrq 👍 and great response time ⚡️
