### ISSUE TITLE
the helptags can not work

### ISSUE THREAD

**Issue by Freed-Wu** [dbmrq/vim-redacted#4]
because the file `redacted.txt` use the char █ , it is not ascii char , so if `helptags` it will return a error about the mixed encoding. I found can avoid this error by rename the file to `redacted.??x` such as `cnx` or `jax`. You can `help helptags` to see more. So can the file be renamed to avoid this error?
Thank you!

**Comment by dbmrq** [comment]
Thank you for letting me know! If you or anyone else can open a PR about this that would be great. Otherwise I'll leave this issue here to remind me to look into it when I have the time.

**Comment by dbmrq** [comment]
Fixed with #5
